### ISSUE TITLE
Invalid lookup source

### ISSUE THREAD

**Issue by AlenPelin** [SitecoreSupport/Sitecore.Support.115854#3]
```
12176 15:52:16 ERROR Failed to update sitecore://master/{03AB0075-1635-4AB9-8C32-5C743632C21B}?lang=en&ver=1 links.
Exception: Sitecore.Exceptions.LookupSourceException
Message: Invalid lookup source "/sitecore/content/_GlobalReferences/FeaturedSectionLogicCollection": Identifier, GUID or "*" expected at position 67..
Source: Sitecore.Support.115854
   at Sitecore.Support.Pipelines.GetLookupSourceTargetItem.GetLookupSourceTargetItemPipeline.Run(GetLookupSourceTargetItemArgs args)
   at Sitecore.Support.Pipelines.GetLookupSourceTargetItem.GetLookupSourceTargetItemPipeline.GetTargetItem(Item item, String source, String fieldValue)
   at Sitecore.Support.Data.Fields.ValueLookupField.ValidateLinks(LinksValidationResult result)
   at Sitecore.Links.ItemLinks.AddLinks(Field field, List`1 links, ItemLinkState linkState)
   at Sitecore.Links.ItemLinks.GetLinks(ItemLinkState linkState, Boolean allVersions, Boolean includeStandardValuesLinks)
   at Sitecore.Links.ItemLinks.GetAllLinks(Boolean allVersions)
   at Sitecore.Links.LinkDatabase.UpdateReferences(Item item)
   at Sitecore.Support.Data.SqlServer.ParallelSqlServerLinkDatabase.TryUpdateItemLinks(Item item)

Nested Exception

Exception: Sitecore.Data.Query.ParseException
Message: Identifier, GUID or "*" expected at position 67.
Source: Sitecore.Kernel
   at Sitecore.Data.Query.QueryParser.Raise(String error)
   at Sitecore.Data.Query.QueryParser.GetElement()
   at Sitecore.Data.Query.QueryParser.GetNode()
   at Sitecore.Data.Query.QueryParser.GetChildren()
   at Sitecore.Data.Query.QueryParser.GetPathStep()
   at Sitecore.Data.Query.QueryParser.GetQuery()
   at Sitecore.Data.Query.QueryParser.GetQueries()
   at Sitecore.Data.Query.QueryParser.DoParse(String query)
   at Sitecore.Data.Query.Query..ctor(String query)
   at Sitecore.Data.Query.Query.SelectSingleItem(String query, QueryContext contextNode, Database database)
   at Sitecore.Support.Pipelines.GetLookupSourceTargetItem.ProcessDefaultSource.Execute(GetLookupSourceTargetItemArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Support.Pipelines.GetLookupSourceTargetItem.GetLookupSourceTargetItemPipeline.Run(GetLookupSourceTargetItemArgs args)
```

**Comment by AlenPelin** [comment]
This error happens with droplist field that exposes datasource as GUID or Item Path.
